### PR TITLE
revert stuttering delay

### LINKED ISSUE #14: Stutter in starting animation towards the end.(Low priority)
I found a stutter in the starting animation that occurs in the new PR, but I don't think occurs, or at least isn't noticable before it.

Not super important, and I would take a stutter if we have something bigger fixed.

### PR DESCRIPTION
**Pull request by lassefolkersen**

### CODE REVIEW

**Comment by lassefolkersen** [comment]
Ok, this should work. Give it a look and a ✅ . It prevents that stuttering thing from #14 , although I do think the intro-sequence is much too quick now. But we can circle back on that later.

**Comment by lionel42** [comment]
I have found this should be refactored using the tick module of pygame.

Let me know if the changes in https://github.com/lassefolkersen/highfrontier/pull/15/commits/79817ded18d87d0422e246f7b31a69b288a24483 make sense to you

**Comment by lassefolkersen** [comment]
Yeah that makes a lot of sense. The `[2, 5]` is probably how it used to be called, I did wonder why one couldn't skip the intro screen. Good work.

**Review by lionel42 — DISMISSED** [review]

**Review by JonathanLochridge — APPROVED** [review]
Looks good,
Stutter is gone.

I did notice the planet rotation freezes for a very short period right before the menu pops, up. But only because I was looking at the intro with a fine toothed comb.

It's normally not noticable, and not big enough to really even be worth in issue. 
And I haven't verified, but I suspect that pause also occurs on older versions anyways, so it isn't caused by any of the recent stuff, so this seems ready.

Good work!

**Pull request merged**
