### PR TITLE
Pyproj update

### PR DESCRIPTION
**Pull request by lionel42**
Updated the old proj binaries with pyproj and many changes related to this.

Just to list here the main things:

* pyproj is used instead of proj
* operations for projections are now vectorized which is much faster (using numpy)
* deleted some temporary files, as now it is not so expensive to recompute them (vectorization + modern hardware) 
*  many refactoring/cleaning

Please let me know what you think about this.

### CODE REVIEW

**Comment by lionel42** [comment]
@lassefolkersen  I had to change the constant in this commit: [4f65379](https://github.com/lassefolkersen/highfrontier/pull/26/commits/4f65379a494f525e276e627bfdc0b18ed08a8ff4) . Do you know where the constant came from ? Did I introduce some error in this pull request ? 
I thought you simply looked at the result, but maybe I am wrong.

**Comment by lassefolkersen** [comment]
> @lassefolkersen I had to change the constant in this commit: [4f65379](https://github.com/lassefolkersen/highfrontier/pull/26/commits/4f65379a494f525e276e627bfdc0b18ed08a8ff4) . Do you know where the constant came from ? Did I introduce some error in this pull request ? I thought you simply looked at the result, but maybe I am wrong.

Impressive work! Let me have a look. It may not be an error. The idea with that test was just to alert if things that were thought to be constant was not. But maybe it's OK under pyproj idk. I'll check it out.

**Comment by lassefolkersen** [comment]
Ok, went through it in detail now. Definetly impressive works. It works so much better for all the non-earth planets (the non pre-calculated). 

The test thing definitely is ignorable. I'm unsure why it happens, but the cities tested (moscow, phoenix) are rendered correctly, so maybe some kind of reference change in pyproj, idk. 

One thing that I do want to investigate further is the resolution. Here's two before (branch master) and after (branch pyproj) screenshots:

Screenshot 2024-05-10 at 08 26 59

Screenshot 2024-05-10 at 08 20 28


As viewed on my local mac. It seems like the most zoomed in round-world projection suffers from a worse resolution now. Which is odd, because as far as I can tell it'd still load in the pre-rendered version. So I can't really tell what happens, but I'm trying to dig into it. Thoughts welcome.

**Comment by lionel42** [comment]
> One thing that I do want to investigate further is the resolution. Here's two before (branch master) and after (branch pyproj) screenshots:

> As viewed on my local mac. It seems like the most zoomed in round-world projection suffers from a worse resolution now. Which is odd, because as far as I can tell it'd still load in the pre-rendered version. So I can't really tell what happens, but I'm trying to dig into it. Thoughts welcome.

I figured out the problem. There was an option `fast_rendering` which basically divides the resolution by 2. 

This was enabled by default, so I switched the default to disabled in [36e97de](https://github.com/lassefolkersen/highfrontier/pull/26/commits/36e97de56286913ee4072beda28a72853d4b5a61) 

It could affect a bit the performance, though I would doubt it to change a lot because of the new vectorization of the operations. 

@lassefolkersen  Let me know if this fixed your resolution issue ;)

**Review by lassefolkersen — APPROVED** [review]
Perfect, I was actually just browsing through something like the same. It's minimal with performance. You put in a few comments about caching which we can explore if need be. But let's go with this. Definitely an advantage to not be dependent on external command line programs.

**Pull request merged**
