### PR TITLE
fixing problem when building as country and selecting very high values for firm size, issue #22

### LINKED ISSUE #22: When playing as country and building a firm the game crashes
The error message is pretty clear. The source is [here](https://github.com/lassefolkersen/highfrontier/blob/fa0566e664e31a01755ad6c45f9f3f650d64872d/gui.py#L3147). And it happens because max_size is smaller than start_value. The only question I can't figure out is why is it like that? Seems to only happen when I select to start as a country, never as a company 
```
228 - value: b'PrintIM\x000250\x00\x00\x02\x00\x02\x00\x01\x00\x00\x00\x01\x01\x00\x00\x00\x00'
225357
3184
basic food production
Traceback (most recent call last):
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 451, in <module>
    introGui = IntroGui()
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 81, in __init__
    self.receive_click(event)
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 105, in receive_click
    button.activate(event)
  File "/Users/lassefolkersen/Documents/highfrontier/gui_components.py", line 499, in activate
    return_value = self.function(self.label, self.function_parameter)
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 444, in start_new_game
    self.main.start_loop(companyName = cn,
  File "/Users/lassefolkersen/Documents/highfrontier/main.py", line 114, in start_loop
    gui_instance.receive_click(event)
  File "/Users/lassefolkersen/Documents/highfrontier/gui.py", line 113, in receive_click
    return_value = self.active_window.receive_click(event)
  File "/Users/lassefolkersen/Documents/highfrontier/gui.py", line 2814, in receive_click
    self.commodity_size_selection(self.fast_list.selected_name)
  File "/Users/lassefolkersen/Documents/highfrontier/gui.py", line 3147, in commodity_size_selection
    raise Exception("This has been observed before. See printout")
Exception: This has been observed before. See printout
```

### LINKED ISSUE #24: When selecting a firm from the list of firms inside a base the game crashes
This happens basically always (as far as I can tell) when selecting a firm. Something about the image for showing in the background of the firm. Maybe idk. Let's find out.

This is the error message
```
Traceback (most recent call last):
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 451, in <module>
    introGui = IntroGui()
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 81, in __init__
    self.receive_click(event)
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 105, in receive_click
    button.activate(event)
  File "/Users/lassefolkersen/Documents/highfrontier/gui_components.py", line 499, in activate
    return_value = self.function(self.label, self.function_parameter)
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 444, in start_new_game
    self.main.start_loop(companyName = cn,
  File "/Users/lassefolkersen/Documents/highfrontier/main.py", line 114, in start_loop
    gui_instance.receive_click(event)
  File "/Users/lassefolkersen/Documents/highfrontier/gui.py", line 116, in receive_click
    self.clear_screen()
  File "/Users/lassefolkersen/Documents/highfrontier/gui.py", line 160, in clear_screen
    self.going_to_firm_window_event(sol.firm_selected)
  File "/Users/lassefolkersen/Documents/highfrontier/gui.py", line 395, in going_to_firm_window_event
    surface = firm_selected.draw_firm_window()
  File "/Users/lassefolkersen/Documents/highfrontier/company.py", line 828, in draw_firm_window
    surface = self.get_firm_background()
  File "/Users/lassefolkersen/Documents/highfrontier/company.py", line 823, in get_firm_background
    image_string = image.tostring()
AttributeError: 'Image' object has no attribute 'tostring'


```

### PR DESCRIPTION
**Pull request by lassefolkersen**
Minor thing, and probably only an issue in some edge case of playing as a country and building a food producing firm right away. But resulted in a crash nonetheless. Now fixed.

### CODE REVIEW

**Comment by JonathanLochridge** [comment]
Do you think this is ready to merge?
I can try to do a test on my end after I look through it an then do the review if you think so?

It looks like a simple and sensible change for addressing it.

**Comment by lassefolkersen** [comment]
I think it's ready to merge, they were really minor things. I guess I should focus on making some more tests, instead of finding these things inside the game.

**Review by lionel42 — APPROVED** [review]

**Comment by lassefolkersen** [comment]
Thanks -- hey @lionel42 @JonathanLochridge if you use twitter, then [check out this one](https://twitter.com/lassefolkersen/status/1788478937997160681) (fun "multiply by 1000 challenge", i did CO2-effects 😄 )

**Comment by JonathanLochridge** [comment]
Well, if you enjoy finding little things in the game, or just happen to run into them while playing then there isn't any issue with trying to fix them as we find them.

**Pull request merged**
