### PR TITLE
Updating to python 3.10

### PR DESCRIPTION
**Pull request by lionel42**
Hi,

I tried to update the game to the latestest python version.
I don't know if you really need to accept that request, as many things are still broken in this version, but if someone is interested they can work on that base.

### CODE REVIEW

**Comment by lassefolkersen** [comment]
This is super cool. I'm going to merge it in, and also have a look at it myself during the holidays. Very cool work, thanks!

**Comment by lionel42** [comment]
Thanks for accepting it !

Just to let you know the main challenges if you work on it:
- I simply used a library to translate from 2 to 3, so many bugs might have appeared from that
- Python 2 had integer division with the char '/' but python3 converts all to float. This has lead to some errors with indexing using floats instead of int. I already solved some bugs but other might be there for that.
- the PIL library has changed a bit and also created some errors.
- pygame controls concerning the constants for which key or which mouse button
- I added controlling the zoom and navigation using the mouse wheel and wasd keys, but I think this also introduced bugs

I hope this will help :)

**Comment by lassefolkersen** [comment]
Yeah, I imagine it could be a lot - I remember there was also something about long integers that ought to have changed. I kinda just gave up back then on bumping it up to 3 because of that, but it's very cool that you've put in work on it

**Comment by JonathanLochridge** [comment]
This is cool, Can't believe it took me two years to notice someone else had tried to work with this.
Updating the version is cool though.

I sort of sat aside the big problem I was working on with it, which kind of transformed into giving up on it over time.

It looks like you  also messed with some loading related stuff, so I am curious about the status of the saving and loading issues?

With your improvements, do we have working saving now? Or was it just redoing some prototype files to make the game load faster or something? not sure?

If we do have it fixed I will probably start playing this again and looking for other potential areas of improvement, expansion, etc.
Although, that might not actually be needed though.

You mentioned there might be some new bugs from this, so I may do some bug hunting and such as I play if saaving is actually fixed. And when I note any I can make issues for them and work towards hopefully resolving them.

If it isn't fixed, I could look at it again, and maybe with your help  we could figure out how to fix that together.

**Pull request merged**
