### PR TITLE
Cleaned some files and some code

### PR DESCRIPTION
**Pull request by lionel42**
Since there have been a bit of activity on the repository, I had some look at the code again and found some time to improve things a bit.

I found that many "ghost" files were there so I removed them so make the repository somewhat lighter. 

Concerning the cleaning, I mainly refactored some parts to make them more modern/understandable.

### CODE REVIEW

**Review by lassefolkersen — APPROVED** [review]
LGTM

**Comment by JonathanLochridge** [comment]
At first I thought you might have removed some stuff that was being used.

But from doublechecking I guess it is just older branches of it we don't need anymore so I guess it's fine. 

company.py in particular seems to have a lot of logic. 

IS the duplicated somewhere else, Or reimplemented/moved by you?

From a bit of skimming that appears like it contains some functions the AI might be calling, As well as helping organize the data connected to each company, I would need to look into it more to verify.

the refactoring of the GUI, display, main, etc. is pretty cool. It reads a bit cleaner. 

I appreciate the further work.

**Comment by JonathanLochridge** [comment]
It throws an error which traces to line 20 of global_variables when I try to run it even inside an environment.
Not sure which of the new changes resulted in that directly.

But it calls on a function that only accepts two arguments but it provides four.
after I do some more verification on other devices I may make a specific issue just for that fatal bug.
```python
standard_font = pygame.font.Font(os.path.join("fonts","freesansbold.ttf"), 13, bold=False, italic=False) #some fonts
``` 
I think that specifying bold and italic as false should be done somewhere else? or not at all, not 100% sure.

Removing that made it start, but now it is crashing on making a new game.

I guess there is a lot of bugs hiding in the new updated version then? I am going to take some time to fix any small but significant bugs that come up trying to test the status of saving again.

The next one is an index out of bound in planet.py that looks a bit more tricky. (At least it is going to take more than 10 minutes to fix like the last one.)

Seems like there is still quite a bit to do to finish the conversion then?

**Comment by lionel42** [comment]
> IS the duplicated somewhere else, Or reimplemented/moved by you?

I removed all what seemed to be obvious duplicated. If we would like to see it again, we can check back on the git history.

**Comment by lionel42** [comment]
> Removing that made it start, but now it is crashing on making a new game.
> 
> I guess there is a lot of bugs hiding in the new updated version then? I am going to take some time to fix any small but significant bugs that come up trying to test the status of saving again.
> 
> The next one is an index out of bound in planet.py that looks a bit more tricky. (At least it is going to take more than 10 minutes to fix like the last one.)
> 
> Seems like there is still quite a bit to do to finish the conversion then?

I just checked, using the most recent version of pygame and there was an issue with the font. I will fix that.

**Pull request merged**
