### PR TITLE
Hopefully fixing save games

### LINKED ISSUE #1: Crash when attempting to load games.
Status: 
Crash on load but not save.

After downloading this program and installing PIL. I was able to get it run smoothly. However, whenever I attempt to save or load a game it crashes. I was able to get it to work without this problem three years ago on a different computer from the Sourceforge link. I am unsure of what is different between that version and the one I have today that is causing the issue. In my folder hunting I have not found been able to find the crash dump yet to try to figure out the issue. 

Also I found it does not do anything when I click the game settings on the main menu.

### PR DESCRIPTION
**Pull request by lassefolkersen**
Hmmmm....seems like something introduced back when threading was done. It seems I literally just needed to stop the thread, save, and then restart it after.

### CODE REVIEW

**Comment by lassefolkersen** [comment]
Ok, seems like this one needs more work. The tests are failing, which is odd - because actually the real game save/load seems to work

**Comment by lassefolkersen** [comment]
Ok, this should work. Give it a look and a ✅ - maybe also do a more full tests yourself first, I only tried once, in a real game - not many edge-cases tested.

**Comment by JonathanLochridge** [comment]
> Ok, seems like this one needs more work. The tests are failing, which is odd - because actually the real game save/load seems to work

So you tested it and were able to load a game properly?
Big step forward if so, I can test on linux as well. Just to be sure.

If this works then I will be super happy!

And GUI will probably be my next focus. 
Along with taking some time to just play it again. (And maybe work on a manual, guide, user documentation, etc.)

**Comment by lassefolkersen** [comment]
Yes, exactly. Tested on mac. But the problem didn't seem platform specific, it was because threading had been introduced later, and that broke the saving. So just had to stop threading while saving and then restarting.

**Comment by JonathanLochridge** [comment]
Multi-threading can be hard to deal with but speed things up a lot, no wonder I couldn't fix it back when I tried a couple years ago.

**Review by JonathanLochridge — APPROVED** [review]
This partially resolves the issue on linux, the first time I tried loading a fresh save it crashed and gave me a smaller error:

<Event(1025-MouseButtonDown {'pos': (572, 472), 'button': 1, 'touch': False, 'window': None})>
Segmentation fault (core dumped)

However, I decided to try loading the same save a second time on the branch and it loaded correctly. 

So this seems to be mostly fixed. Not sure where the core dumped on that one-off error goes, if feasible I would like to have that checked. But this seems to achieve the main goal. So, we should be able to merge and close the associated issue?

**Comment by lassefolkersen** [comment]
OK let's, and let's see if that segmentation fault happens again, and if so make a new issue out of it. I haven't seen that (yet)

**Comment by JonathanLochridge** [comment]
If I spot it come up again rather than a 1-off I will make an issue.

**Pull request merged**
